<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Support\Str;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        // Create categories
        $bahanBaku = Category::create([
            'name' => 'Bahan Baku',
            'slug' => 'bahan-baku',
            'type' => 'bahan_baku',
            'description' => 'Bahan baku untuk produksi cat',
        ]);

        $packaging = Category::create([
            'name' => 'Material/Packaging',
            'slug' => 'packaging',
            'type' => 'packaging',
            'description' => 'Material dan packaging produksi',
        ]);

        $barangJadi = Category::create([
            'name' => 'Barang Jadi',
            'slug' => 'barang-jadi',
            'type' => 'barang_jadi',
            'description' => 'Produk jadi siap jual',
        ]);

        // =========================================
        // BAHAN BAKU - 100 ITEMS
        // =========================================
        $bahanBakuItems = [
            // High Spec Raw Materials (50 items)
            ['name' => 'Titanium Dioxide Premium', 'code' => 'BB-TDP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Resin Akrilik High Grade', 'code' => 'BB-RAH', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Solvent Thinner Premium', 'code' => 'BB-STP', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Pigment Merah Oxide', 'code' => 'BB-PMO', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Pigment Kuning Chrome', 'code' => 'BB-PKC', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Pigment Biru Cobalt', 'code' => 'BB-PBC', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Pigment Hijau Emerald', 'code' => 'BB-PHE', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Pigment Hitam Carbon', 'code' => 'BB-PHC', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Resin Alkyd Premium', 'code' => 'BB-RAP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Resin Epoxy Grade A', 'code' => 'BB-REA', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Resin Polyurethane', 'code' => 'BB-RPU', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Binder Acrylic Premium', 'code' => 'BB-BAP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Dispersant Ultra', 'code' => 'BB-DIS', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Defoamer Premium', 'code' => 'BB-DFP', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Coalescent Agent', 'code' => 'BB-COA', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Thickener Rheology', 'code' => 'BB-THR', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Biocide Premium', 'code' => 'BB-BIO', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'UV Absorber', 'code' => 'BB-UVA', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Anti-settling Agent', 'code' => 'BB-ASA', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Flash Rust Inhibitor', 'code' => 'BB-FRI', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Pigment Orange Cadmium', 'code' => 'BB-POC', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Pigment Violet Ultramarine', 'code' => 'BB-PVU', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Pigment Brown Iron', 'code' => 'BB-PBI', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Zinc Oxide Premium', 'code' => 'BB-ZOP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Zinc Phosphate', 'code' => 'BB-ZPH', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Silica Fumed', 'code' => 'BB-SIF', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Silica Precipitated', 'code' => 'BB-SIP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Mica Pearl', 'code' => 'BB-MIP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Aluminum Paste', 'code' => 'BB-ALP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Bronze Powder', 'code' => 'BB-BRP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Matting Agent', 'code' => 'BB-MAT', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Flow Agent Premium', 'code' => 'BB-FAP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Wetting Agent', 'code' => 'BB-WEA', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Leveling Agent', 'code' => 'BB-LEA', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Slip Additive', 'code' => 'BB-SLA', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Scratch Resistant Additive', 'code' => 'BB-SRA', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Hardener Epoxy', 'code' => 'BB-HEP', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Hardener Polyurethane', 'code' => 'BB-HPU', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Catalyst Alkyd', 'code' => 'BB-CAL', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Drier Cobalt', 'code' => 'BB-DCO', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Drier Manganese', 'code' => 'BB-DMN', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Drier Zirconium', 'code' => 'BB-DZR', 'unit' => 'kg', 'spec' => 'high_spec'],
            ['name' => 'Xylene Premium', 'code' => 'BB-XYP', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Toluene Premium', 'code' => 'BB-TOP', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Butyl Acetate', 'code' => 'BB-BUA', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Ethyl Acetate', 'code' => 'BB-ETA', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'MEK Premium', 'code' => 'BB-MEK', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Isopropyl Alcohol', 'code' => 'BB-IPA', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'Butanol Premium', 'code' => 'BB-BUP', 'unit' => 'liter', 'spec' => 'high_spec'],
            ['name' => 'PMA Solvent', 'code' => 'BB-PMA', 'unit' => 'liter', 'spec' => 'high_spec'],
            // Medium Spec Raw Materials (50 items)
            ['name' => 'Kaolin Standard', 'code' => 'BB-KST', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Calcium Carbonate', 'code' => 'BB-CCB', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Solvent Thinner Standard', 'code' => 'BB-STS', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Talc Powder', 'code' => 'BB-TLP', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Barium Sulfate', 'code' => 'BB-BSF', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Dolomite Powder', 'code' => 'BB-DLP', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Feldspar Powder', 'code' => 'BB-FLP', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Whiting Chalk', 'code' => 'BB-WCH', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'China Clay', 'code' => 'BB-CCL', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Silica Sand', 'code' => 'BB-SSA', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Marble Powder', 'code' => 'BB-MRP', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Bentonite Clay', 'code' => 'BB-BCL', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Attapulgite Clay', 'code' => 'BB-ACL', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Resin Alkyd Standard', 'code' => 'BB-RAS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Resin Acrylic Standard', 'code' => 'BB-RACS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Pigment Putih Standard', 'code' => 'BB-PPS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Pigment Merah Standard', 'code' => 'BB-PMS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Pigment Kuning Standard', 'code' => 'BB-PKS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Pigment Biru Standard', 'code' => 'BB-PBS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Pigment Hijau Standard', 'code' => 'BB-PHS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Pigment Hitam Standard', 'code' => 'BB-PHTS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Cellulose Thickener', 'code' => 'BB-CTH', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'HEC Thickener', 'code' => 'BB-HEC', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Defoamer Standard', 'code' => 'BB-DFS', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Dispersant Standard', 'code' => 'BB-DSS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Wetting Agent Standard', 'code' => 'BB-WAS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Biocide Standard', 'code' => 'BB-BIS', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Ammonia Solution', 'code' => 'BB-AMS', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Propylene Glycol', 'code' => 'BB-PGL', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Ethylene Glycol', 'code' => 'BB-EGL', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Texanol Standard', 'code' => 'BB-TXS', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Mineral Spirit', 'code' => 'BB-MSP', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'White Spirit', 'code' => 'BB-WSP', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Turpentine Oil', 'code' => 'BB-TUO', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Kerosene Deodorized', 'code' => 'BB-KRD', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Zinc Dust', 'code' => 'BB-ZND', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Iron Oxide Yellow', 'code' => 'BB-IOY', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Iron Oxide Red', 'code' => 'BB-IOR', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Iron Oxide Black', 'code' => 'BB-IOB', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Lamp Black', 'code' => 'BB-LBK', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Lithopone', 'code' => 'BB-LIT', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Lead Free Drier', 'code' => 'BB-LFD', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Castor Oil', 'code' => 'BB-CSO', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Linseed Oil', 'code' => 'BB-LSO', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Soybean Oil Modified', 'code' => 'BB-SBM', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Tall Oil', 'code' => 'BB-TAO', 'unit' => 'liter', 'spec' => 'medium_spec'],
            ['name' => 'Rosin Ester', 'code' => 'BB-RSE', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Maleic Resin', 'code' => 'BB-MRE', 'unit' => 'kg', 'spec' => 'medium_spec'],
            ['name' => 'Phenolic Resin', 'code' => 'BB-PRE', 'unit' => 'kg', 'spec' => 'medium_spec'],
        ];

        foreach ($bahanBakuItems as $i => $item) {
            Product::create([
                'uuid' => Str::uuid()->toString(),
                'category_id' => $bahanBaku->id,
                'name' => $item['name'],
                'code' => $item['code'] . '-' . str_pad($i + 1, 3, '0', STR_PAD_LEFT),
                'unit' => $item['unit'],
                'current_stock' => rand(50, 1000),
                'min_stock' => rand(20, 150),
                'spec_type' => $item['spec'],
                'supplier_type' => ['supplier_resmi', 'agen', 'internal'][rand(0, 2)],
            ]);
        }

        // =========================================
        // MATERIAL/PACKAGING - 100 ITEMS
        // =========================================
        $packagingItems = [
            ['name' => 'Kaleng 1 Liter', 'code' => 'PK-K1L', 'unit' => 'pcs'],
            ['name' => 'Kaleng 2.5 Liter', 'code' => 'PK-K25L', 'unit' => 'pcs'],
            ['name' => 'Kaleng 5 Liter', 'code' => 'PK-K5L', 'unit' => 'pcs'],
            ['name' => 'Kaleng 10 Liter', 'code' => 'PK-K10L', 'unit' => 'pcs'],
            ['name' => 'Kaleng 20 Liter', 'code' => 'PK-K20L', 'unit' => 'pcs'],
            ['name' => 'Pail Plastik 5 Kg', 'code' => 'PK-PP5K', 'unit' => 'pcs'],
            ['name' => 'Pail Plastik 10 Kg', 'code' => 'PK-PP10K', 'unit' => 'pcs'],
            ['name' => 'Pail Plastik 20 Kg', 'code' => 'PK-PP20K', 'unit' => 'pcs'],
            ['name' => 'Pail Plastik 25 Kg', 'code' => 'PK-PP25K', 'unit' => 'pcs'],
            ['name' => 'Drum Besi 200 Liter', 'code' => 'PK-DB200', 'unit' => 'pcs'],
            ['name' => 'Drum Plastik 200 Liter', 'code' => 'PK-DP200', 'unit' => 'pcs'],
            ['name' => 'IBC Tank 1000 Liter', 'code' => 'PK-IBC1K', 'unit' => 'pcs'],
            ['name' => 'Jerigen 5 Liter', 'code' => 'PK-JR5L', 'unit' => 'pcs'],
            ['name' => 'Jerigen 10 Liter', 'code' => 'PK-JR10L', 'unit' => 'pcs'],
            ['name' => 'Jerigen 20 Liter', 'code' => 'PK-JR20L', 'unit' => 'pcs'],
            ['name' => 'Jerigen 25 Liter', 'code' => 'PK-JR25L', 'unit' => 'pcs'],
            ['name' => 'Botol Plastik 250ml', 'code' => 'PK-BP250', 'unit' => 'pcs'],
            ['name' => 'Botol Plastik 500ml', 'code' => 'PK-BP500', 'unit' => 'pcs'],
            ['name' => 'Botol Plastik 1000ml', 'code' => 'PK-BP1K', 'unit' => 'pcs'],
            ['name' => 'Tutup Kaleng 1L', 'code' => 'PK-TK1L', 'unit' => 'pcs'],
            ['name' => 'Tutup Kaleng 5L', 'code' => 'PK-TK5L', 'unit' => 'pcs'],
            ['name' => 'Tutup Kaleng 20L', 'code' => 'PK-TK20L', 'unit' => 'pcs'],
            ['name' => 'Tutup Pail Plastik', 'code' => 'PK-TPP', 'unit' => 'pcs'],
            ['name' => 'Tutup Drum', 'code' => 'PK-TDR', 'unit' => 'pcs'],
            ['name' => 'Seal Ring Kaleng', 'code' => 'PK-SRK', 'unit' => 'pcs'],
            ['name' => 'Seal Ring Drum', 'code' => 'PK-SRD', 'unit' => 'pcs'],
            ['name' => 'Gasket Tutup', 'code' => 'PK-GST', 'unit' => 'pcs'],
            ['name' => 'Label Sticker 1L', 'code' => 'PK-LS1L', 'unit' => 'lembar'],
            ['name' => 'Label Sticker 5L', 'code' => 'PK-LS5L', 'unit' => 'lembar'],
            ['name' => 'Label Sticker 20L', 'code' => 'PK-LS20L', 'unit' => 'lembar'],
            ['name' => 'Label Sticker Pail', 'code' => 'PK-LSP', 'unit' => 'lembar'],
            ['name' => 'Label Karton', 'code' => 'PK-LKT', 'unit' => 'lembar'],
            ['name' => 'Hang Tag', 'code' => 'PK-HTG', 'unit' => 'pcs'],
            ['name' => 'Karton Box Single Wall', 'code' => 'PK-KBSW', 'unit' => 'pcs'],
            ['name' => 'Karton Box Double Wall', 'code' => 'PK-KBDW', 'unit' => 'pcs'],
            ['name' => 'Karton Box Triple Wall', 'code' => 'PK-KBTW', 'unit' => 'pcs'],
            ['name' => 'Karton Partisi', 'code' => 'PK-KPT', 'unit' => 'pcs'],
            ['name' => 'Bubble Wrap Roll', 'code' => 'PK-BWR', 'unit' => 'roll'],
            ['name' => 'Stretch Film', 'code' => 'PK-STF', 'unit' => 'roll'],
            ['name' => 'Shrink Wrap', 'code' => 'PK-SHW', 'unit' => 'roll'],
            ['name' => 'Strapping Band', 'code' => 'PK-SBD', 'unit' => 'roll'],
            ['name' => 'Strapping Clip', 'code' => 'PK-SCP', 'unit' => 'pcs'],
            ['name' => 'Pallet Kayu Standard', 'code' => 'PK-PKS', 'unit' => 'pcs'],
            ['name' => 'Pallet Kayu Euro', 'code' => 'PK-PKE', 'unit' => 'pcs'],
            ['name' => 'Pallet Plastik', 'code' => 'PK-PPL', 'unit' => 'pcs'],
            ['name' => 'Lakban Coklat', 'code' => 'PK-LBC', 'unit' => 'roll'],
            ['name' => 'Lakban Bening', 'code' => 'PK-LBG', 'unit' => 'roll'],
            ['name' => 'Lakban Fragile', 'code' => 'PK-LFR', 'unit' => 'roll'],
            ['name' => 'Plastik PE 0.03mm', 'code' => 'PK-PE03', 'unit' => 'kg'],
            ['name' => 'Plastik PE 0.05mm', 'code' => 'PK-PE05', 'unit' => 'kg'],
            ['name' => 'Plastik PE 0.08mm', 'code' => 'PK-PE08', 'unit' => 'kg'],
            ['name' => 'Plastik Cor', 'code' => 'PK-PCR', 'unit' => 'roll'],
            ['name' => 'Karet Gelang', 'code' => 'PK-KGL', 'unit' => 'kg'],
            ['name' => 'Tali Rafia', 'code' => 'PK-TRF', 'unit' => 'kg'],
            ['name' => 'Tali Tambang', 'code' => 'PK-TTB', 'unit' => 'meter'],
            ['name' => 'Silica Gel Sachet', 'code' => 'PK-SGS', 'unit' => 'pcs'],
            ['name' => 'Desiccant Bag', 'code' => 'PK-DSB', 'unit' => 'pcs'],
            ['name' => 'Baut Tutup Drum', 'code' => 'PK-BTD', 'unit' => 'pcs'],
            ['name' => 'Kunci Drum', 'code' => 'PK-KDR', 'unit' => 'pcs'],
            ['name' => 'Handle Plastik', 'code' => 'PK-HPL', 'unit' => 'pcs'],
            ['name' => 'Handle Kaleng', 'code' => 'PK-HKL', 'unit' => 'pcs'],
            ['name' => 'Spout Pour Cap', 'code' => 'PK-SPC', 'unit' => 'pcs'],
            ['name' => 'Flex Spout', 'code' => 'PK-FSP', 'unit' => 'pcs'],
            ['name' => 'Safety Seal', 'code' => 'PK-SFS', 'unit' => 'pcs'],
            ['name' => 'Tamper Evident Band', 'code' => 'PK-TEB', 'unit' => 'pcs'],
            ['name' => 'Induction Seal Liner', 'code' => 'PK-ISL', 'unit' => 'pcs'],
            ['name' => 'Foam Liner', 'code' => 'PK-FML', 'unit' => 'pcs'],
            ['name' => 'Pressure Sensitive Liner', 'code' => 'PK-PSL', 'unit' => 'pcs'],
            ['name' => 'Color Card Sample', 'code' => 'PK-CCS', 'unit' => 'pcs'],
            ['name' => 'Brosur Produk', 'code' => 'PK-BRP', 'unit' => 'lembar'],
            ['name' => 'Katalog Warna', 'code' => 'PK-KTW', 'unit' => 'pcs'],
            ['name' => 'Technical Data Sheet', 'code' => 'PK-TDS', 'unit' => 'lembar'],
            ['name' => 'MSDS Sheet', 'code' => 'PK-MSD', 'unit' => 'lembar'],
            ['name' => 'COA Certificate', 'code' => 'PK-COA', 'unit' => 'lembar'],
            ['name' => 'Stiker QC Pass', 'code' => 'PK-SQC', 'unit' => 'lembar'],
            ['name' => 'Stiker Batch Number', 'code' => 'PK-SBN', 'unit' => 'roll'],
            ['name' => 'Stiker Barcode', 'code' => 'PK-SBC', 'unit' => 'roll'],
            ['name' => 'Stiker Expire Date', 'code' => 'PK-SED', 'unit' => 'roll'],
            ['name' => 'Stiker Warning', 'code' => 'PK-SWR', 'unit' => 'lembar'],
            ['name' => 'Stiker Flammable', 'code' => 'PK-SFL', 'unit' => 'lembar'],
            ['name' => 'Stiker Corrosive', 'code' => 'PK-SCR', 'unit' => 'lembar'],
            ['name' => 'Stiker Toxic', 'code' => 'PK-STX', 'unit' => 'lembar'],
            ['name' => 'Inner Box', 'code' => 'PK-INB', 'unit' => 'pcs'],
            ['name' => 'Outer Master Box', 'code' => 'PK-OMB', 'unit' => 'pcs'],
            ['name' => 'Insert Foam', 'code' => 'PK-IFM', 'unit' => 'pcs'],
            ['name' => 'Corner Protector', 'code' => 'PK-CPT', 'unit' => 'pcs'],
            ['name' => 'Edge Protector', 'code' => 'PK-EPT', 'unit' => 'meter'],
            ['name' => 'Cardboard Sheet', 'code' => 'PK-CBS', 'unit' => 'lembar'],
            ['name' => 'Kraft Paper Roll', 'code' => 'PK-KPR', 'unit' => 'roll'],
            ['name' => 'Wax Paper', 'code' => 'PK-WXP', 'unit' => 'roll'],
            ['name' => 'VCI Paper', 'code' => 'PK-VCI', 'unit' => 'roll'],
            ['name' => 'Poly Bag Small', 'code' => 'PK-PBS', 'unit' => 'pcs'],
            ['name' => 'Poly Bag Medium', 'code' => 'PK-PBM', 'unit' => 'pcs'],
            ['name' => 'Poly Bag Large', 'code' => 'PK-PBL', 'unit' => 'pcs'],
            ['name' => 'Zip Lock Bag', 'code' => 'PK-ZLB', 'unit' => 'pcs'],
            ['name' => 'Vacuum Bag', 'code' => 'PK-VCB', 'unit' => 'pcs'],
            ['name' => 'Aluminum Foil Bag', 'code' => 'PK-AFB', 'unit' => 'pcs'],
        ];

        foreach ($packagingItems as $i => $item) {
            Product::create([
                'uuid' => Str::uuid()->toString(),
                'category_id' => $packaging->id,
                'name' => $item['name'],
                'code' => $item['code'] . '-' . str_pad($i + 1, 3, '0', STR_PAD_LEFT),
                'unit' => $item['unit'],
                'current_stock' => rand(100, 5000),
                'min_stock' => rand(50, 500),
                'spec_type' => null,
            ]);
        }

        // =========================================
        // BARANG JADI - 50 ITEMS
        // =========================================
        $barangJadiItems = [
            ['name' => 'Cat Tembok Putih Premium 5L', 'code' => 'BJ-CTP5'],
            ['name' => 'Cat Tembok Putih Premium 20L', 'code' => 'BJ-CTP20'],
            ['name' => 'Cat Tembok Putih Ekonomi 5L', 'code' => 'BJ-CTE5'],
            ['name' => 'Cat Tembok Putih Ekonomi 20L', 'code' => 'BJ-CTE20'],
            ['name' => 'Cat Tembok Warna Pastel 5L', 'code' => 'BJ-CTWP5'],
            ['name' => 'Cat Tembok Warna Pastel 20L', 'code' => 'BJ-CTWP20'],
            ['name' => 'Cat Tembok Warna Bold 5L', 'code' => 'BJ-CTWB5'],
            ['name' => 'Cat Tembok Warna Bold 20L', 'code' => 'BJ-CTWB20'],
            ['name' => 'Cat Tembok Anti Jamur 5L', 'code' => 'BJ-CTAJ5'],
            ['name' => 'Cat Tembok Anti Bocor 5L', 'code' => 'BJ-CTAB5'],
            ['name' => 'Cat Tembok Exterior 5L', 'code' => 'BJ-CTEX5'],
            ['name' => 'Cat Tembok Exterior 20L', 'code' => 'BJ-CTEX20'],
            ['name' => 'Cat Minyak Glossy Putih 1L', 'code' => 'BJ-CMGP1'],
            ['name' => 'Cat Minyak Glossy Putih 5L', 'code' => 'BJ-CMGP5'],
            ['name' => 'Cat Minyak Glossy Warna 1L', 'code' => 'BJ-CMGW1'],
            ['name' => 'Cat Minyak Glossy Warna 5L', 'code' => 'BJ-CMGW5'],
            ['name' => 'Cat Minyak Doff 1L', 'code' => 'BJ-CMD1'],
            ['name' => 'Cat Minyak Doff 5L', 'code' => 'BJ-CMD5'],
            ['name' => 'Cat Kayu Pernis Clear 1L', 'code' => 'BJ-CKP1'],
            ['name' => 'Cat Kayu Pernis Clear 5L', 'code' => 'BJ-CKP5'],
            ['name' => 'Cat Kayu Pernis Warna 1L', 'code' => 'BJ-CKPW1'],
            ['name' => 'Cat Kayu Warna Solid 1L', 'code' => 'BJ-CKWS1'],
            ['name' => 'Cat Besi Anti Karat 1L', 'code' => 'BJ-CBAK1'],
            ['name' => 'Cat Besi Anti Karat 5L', 'code' => 'BJ-CBAK5'],
            ['name' => 'Cat Besi Hammer Finish 1L', 'code' => 'BJ-CBHF1'],
            ['name' => 'Cat Epoxy Lantai 5L', 'code' => 'BJ-CEL5'],
            ['name' => 'Cat Epoxy Lantai 20L', 'code' => 'BJ-CEL20'],
            ['name' => 'Cat Floor Coating 5L', 'code' => 'BJ-CFC5'],
            ['name' => 'Cat Glow In Dark 500ml', 'code' => 'BJ-CGD500'],
            ['name' => 'Cat Chalkboard 1L', 'code' => 'BJ-CCB1'],
            ['name' => 'Cat Magnetic 1L', 'code' => 'BJ-CMG1'],
            ['name' => 'Cat Tekstur Pasir 20L', 'code' => 'BJ-CTP20L'],
            ['name' => 'Cat Tekstur Marmer 20L', 'code' => 'BJ-CTM20'],
            ['name' => 'Primer Alkali Resisting 5L', 'code' => 'BJ-PAR5'],
            ['name' => 'Primer Sealer 5L', 'code' => 'BJ-PS5'],
            ['name' => 'Primer Zinc Chromate 5L', 'code' => 'BJ-PZC5'],
            ['name' => 'Primer Red Oxide 5L', 'code' => 'BJ-PRO5'],
            ['name' => 'Primer Epoxy 5L', 'code' => 'BJ-PEP5'],
            ['name' => 'Thinner A Special 5L', 'code' => 'BJ-TAS5'],
            ['name' => 'Thinner A Special 20L', 'code' => 'BJ-TAS20'],
            ['name' => 'Thinner B Standard 5L', 'code' => 'BJ-TBS5'],
            ['name' => 'Thinner B Standard 20L', 'code' => 'BJ-TBS20'],
            ['name' => 'Thinner NC Lacquer 5L', 'code' => 'BJ-TNL5'],
            ['name' => 'Thinner PU 5L', 'code' => 'BJ-TPU5'],
            ['name' => 'Thinner Epoxy 5L', 'code' => 'BJ-TEP5'],
            ['name' => 'Wood Stain Dark Oak 1L', 'code' => 'BJ-WSDO1'],
            ['name' => 'Wood Stain Mahogany 1L', 'code' => 'BJ-WSM1'],
            ['name' => 'Wood Stain Walnut 1L', 'code' => 'BJ-WSW1'],
            ['name' => 'Wood Filler 1L', 'code' => 'BJ-WF1'],
            ['name' => 'Plamir Tembok 5L', 'code' => 'BJ-PT5'],
        ];

        foreach ($barangJadiItems as $i => $item) {
            Product::create([
                'uuid' => Str::uuid()->toString(),
                'category_id' => $barangJadi->id,
                'name' => $item['name'],
                'code' => $item['code'] . '-' . str_pad($i + 1, 3, '0', STR_PAD_LEFT),
                'unit' => 'pcs',
                'current_stock' => rand(20, 500),
                'min_stock' => rand(10, 100),
                'spec_type' => null,
            ]);
        }
    }
}
